// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCD9KFmnpEuVPGJOEUte6iUpIiH-sW3YvA',
    appId: '1:18105285108:web:9af6c8752702d269ed21a1',
    messagingSenderId: '18105285108',
    projectId: 'assessmnet-fdfdb',
    authDomain: 'assessmnet-fdfdb.firebaseapp.com',
    storageBucket: 'assessmnet-fdfdb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtVkuGHwhnGjPVfIsD0yjJ5XIlN0XrHNI',
    appId: '1:18105285108:android:013bc0ad241d5d8ced21a1',
    messagingSenderId: '18105285108',
    projectId: 'assessmnet-fdfdb',
    storageBucket: 'assessmnet-fdfdb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFNwMye0PEfrcP2Q6PUn6UO17RTfqFMd8',
    appId: '1:18105285108:ios:acfeb7c346a129aded21a1',
    messagingSenderId: '18105285108',
    projectId: 'assessmnet-fdfdb',
    storageBucket: 'assessmnet-fdfdb.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFNwMye0PEfrcP2Q6PUn6UO17RTfqFMd8',
    appId: '1:18105285108:ios:acfeb7c346a129aded21a1',
    messagingSenderId: '18105285108',
    projectId: 'assessmnet-fdfdb',
    storageBucket: 'assessmnet-fdfdb.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCD9KFmnpEuVPGJOEUte6iUpIiH-sW3YvA',
    appId: '1:18105285108:web:19844fcb4988e1b6ed21a1',
    messagingSenderId: '18105285108',
    projectId: 'assessmnet-fdfdb',
    authDomain: 'assessmnet-fdfdb.firebaseapp.com',
    storageBucket: 'assessmnet-fdfdb.firebasestorage.app',
  );
}
